### ISSUE TITLE
SOAP version has security vulnerability in dependency ejs

### ISSUE THREAD

**Issue by tr90814** [TimeBandit/charity-commission-api#1]
The current version of the `SOAP` npm package used (0.16.0) relies on a version of `ejs` that has a [security vulnerability](https://github.com/mde/ejs/issues/323).

I have a patch version bump PR ready to go if you give me push access @TimeBandit .

**Comment by TimeBandit** [comment]
Hi Tom, I've assigned it to you. Please give that a go. It's the first time I'm assigning an issue to someone so please do let me know if it gives you correct permissions :+1:

**Comment by tr90814** [comment]
Hello! It was my fault actually - forgot I needed to fork the repo in order to suggest a PR.

**Comment by TimeBandit** [comment]
Package version bumped. If you know anyone who would consider becoming a package maintainer do let me know. Bye :+1:
